# Generated by Django 3.0.10 on 2020-10-25 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('lunch_type', models.CharField(choices=[('HOT LUNCH', 'Hot Lunch'), ('COLD LUNCH', 'Cold Lunch'), ('FIELD TRIP LUNCH', 'Field Trip Lunch')], default='COLD LUNCH', max_length=20)),
                ('parent_attendance', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections_created', to=settings.AUTH_USER_MODEL)),
                ('users_like', models.ManyToManyField(blank=True, related_name='selections_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
